server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuyiwen98/aispringcloud.git
          searchPaths: config
          username: 190848486@qq.com
          password: qwsxyw0421
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
